# Generated by Django 3.1.7 on 2021-04-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.URLField(default='https://cdn.pixabay.com/photo/2016/08/31/11/54/user-1633249_960_720.png'),
            preserve_default=False,
        ),
    ]
