# Generated by Django 3.1.7 on 2021-04-20 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_auto_20210420_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestones',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendars.goals'),
        ),
    ]
